
/*
Tabla aerolíneas
*/
CREATE TABLE aerolineas (
    ID_AEROLINEA int(3) NOT NULL AUTO_INCREMENT,
    NOMBRE_AEROLINEA varchar(30) NOT NULL,
    CONSTRAINT PK_aerolinea PRIMARY KEY (ID_AEROLINEA)
);

/*
Tabla aeropuertos
*/
CREATE TABLE aeropuertos (
    ID_AEROPUERTO int(3) NOT NULL AUTO_INCREMENT,
    NOMBRE_AEROPUERTO varchar(30) NOT NULL,
    CONSTRAINT PK_aeropuerto PRIMARY KEY (ID_AEROPUERTO)
);

/*
Tabla movimientos
*/
CREATE TABLE movimientos (
    ID_MOVIMIENTO int(3) NOT NULL AUTO_INCREMENT,
    DESCRIPCION varchar(30) NOT NULL,
    CONSTRAINT PK_movimiento PRIMARY KEY (ID_MOVIMIENTO)
);

/*
Tabla vuelos
*/
CREATE TABLE vuelos (
    DIA date NOT NULL,
    ID_AEROLINEA int(3) NOT NULL,
    ID_AEROPUERTO int(3) NOT NULL,
    ID_MOVIMIENTO int(3) NOT NULL,
    CONSTRAINT FK_aerolinea FOREIGN KEY (ID_AEROLINEA) REFERENCES aerolineas(ID_AEROLINEA),
    CONSTRAINT FK_aeropuerto FOREIGN KEY (ID_AEROPUERTO) REFERENCES aeropuertos(ID_AEROPUERTO),
    CONSTRAINT FK_movimiento FOREIGN KEY (ID_MOVIMIENTO) REFERENCES movimientos(ID_MOVIMIENTO)
);

INSERT INTO aerolineas (NOMBRE_AEROLINEA) VALUES ('Volaris');
INSERT INTO aerolineas (NOMBRE_AEROLINEA) VALUES ('Aeromar');
INSERT INTO aerolineas (NOMBRE_AEROLINEA) VALUES ('Interjet');
INSERT INTO aerolineas (NOMBRE_AEROLINEA) VALUES ('Aeromexico');

INSERT INTO aeropuertos (NOMBRE_AEROPUERTO) VALUES ('Benito Juarez');
INSERT INTO aeropuertos (NOMBRE_AEROPUERTO) VALUES ('Guanajuato');
INSERT INTO aeropuertos (NOMBRE_AEROPUERTO) VALUES ('La paz');
INSERT INTO aeropuertos (NOMBRE_AEROPUERTO) VALUES ('Oaxaca');

INSERT INTO movimientos (DESCRIPCION) VALUES ('Salida');
INSERT INTO movimientos (DESCRIPCION) VALUES ('Llegada');

INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (1, 1, 1, '2021-05-02');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (2, 1, 1, '2021-05-02');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (3, 2, 2, '2021-05-02');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (4, 3, 2, '2021-05-02');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (1, 3, 2, '2021-05-02');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (2, 1, 1, '2021-05-02');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (2, 3, 1, '2021-05-04');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (3, 4, 1, '2021-05-04');
INSERT INTO vuelos (ID_AEROLINEA, ID_AEROPUERTO, ID_MOVIMIENTO, DIA) VALUES (3, 4, 1, '2021-05-04');